-- 家教发布内容表：需先执行 tutor_parent_profile.sql、tutor_teacher_profile.sql

CREATE TABLE IF NOT EXISTS `tutor_demand` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '家长需求编号',
  `user_id` bigint NOT NULL COMMENT '会员用户编号',
  `title` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标题',
  `grade` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '年级',
  `subjects` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '科目，多个用逗号分隔',
  `teach_mode` tinyint NOT NULL COMMENT '授课模式：1 上门，2 在线，3 均可',
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '详细上课地址',
  `budget_min` int NOT NULL DEFAULT 0 COMMENT '最低预算',
  `budget_max` int NOT NULL DEFAULT 0 COMMENT '最高预算',
  `description` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '详细要求',
  `city_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '城市编码',
  `city_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '城市名称',
  `longitude` decimal(10,6) NULL DEFAULT NULL COMMENT '授课位置经度',
  `latitude` decimal(10,6) NULL DEFAULT NULL COMMENT '授课位置纬度',
  `distance_visible` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否显示距离',
  `contact_mobile_encrypt` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '联系手机号加密值',
  `contact_mobile_mask` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '联系手机号脱敏值',
  `contact_wechat_encrypt` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '联系微信加密值',
  `contact_wechat_mask` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '联系微信脱敏值',
  `status` tinyint NOT NULL DEFAULT 10 COMMENT '发布状态：10 待审核，20 展示中，30 审核拒绝，40 已下架',
  `audit_status` tinyint NOT NULL DEFAULT 10 COMMENT '审核状态：10 待审核，20 通过，30 拒绝',
  `reject_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '拒绝原因',
  `view_count` int NOT NULL DEFAULT 0 COMMENT '浏览次数',
  `contact_view_count` int NOT NULL DEFAULT 0 COMMENT '联系方式查看次数',
  `match_count` int NOT NULL DEFAULT 0 COMMENT '匹配成功次数',
  `expire_time` datetime NOT NULL COMMENT '过期时间',
  `top_until` datetime NULL DEFAULT NULL COMMENT '置顶截止时间',
  `urgent_until` datetime NULL DEFAULT NULL COMMENT '加急截止时间',
  `boost_until` datetime NULL DEFAULT NULL COMMENT '加速截止时间',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tutor_demand_user_status` (`user_id`, `status`) USING BTREE,
  KEY `idx_tutor_demand_audit` (`audit_status`, `create_time`) USING BTREE,
  KEY `idx_tutor_demand_square` (`city_code`, `status`, `expire_time`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '家教家长需求表';

CREATE TABLE IF NOT EXISTS `tutor_teacher_resume` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '教师简历编号',
  `user_id` bigint NOT NULL COMMENT '会员用户编号',
  `title` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标题',
  `subjects` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '科目，多个用逗号分隔',
  `teach_modes` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '授课模式，多个用逗号分隔',
  `hourly_price` int NOT NULL DEFAULT 0 COMMENT '时薪',
  `free_trial_enabled` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否支持试课',
  `free_trial_minutes` int NOT NULL DEFAULT 0 COMMENT '试课时长，单位分钟',
  `teaching_experience` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '教学经验',
  `available_times` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '可授课时间',
  `city_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '城市编码',
  `city_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '城市名称',
  `longitude` decimal(10,6) NULL DEFAULT NULL COMMENT '服务位置经度',
  `latitude` decimal(10,6) NULL DEFAULT NULL COMMENT '服务位置纬度',
  `service_radius_km` int NOT NULL DEFAULT 0 COMMENT '服务半径，单位公里',
  `contact_mobile_encrypt` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '联系手机号加密值',
  `contact_mobile_mask` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '联系手机号脱敏值',
  `contact_wechat_encrypt` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '联系微信加密值',
  `contact_wechat_mask` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '联系微信脱敏值',
  `status` tinyint NOT NULL DEFAULT 10 COMMENT '发布状态：10 待审核，20 展示中，30 审核拒绝，40 已下架',
  `audit_status` tinyint NOT NULL DEFAULT 10 COMMENT '审核状态：10 待审核，20 通过，30 拒绝',
  `reject_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '拒绝原因',
  `rating_avg` decimal(4,2) NOT NULL DEFAULT 0.00 COMMENT '平均评分',
  `review_count` int NOT NULL DEFAULT 0 COMMENT '评价数',
  `view_count` int NOT NULL DEFAULT 0 COMMENT '浏览次数',
  `contact_view_count` int NOT NULL DEFAULT 0 COMMENT '联系方式查看次数',
  `match_count` int NOT NULL DEFAULT 0 COMMENT '匹配成功次数',
  `top_until` datetime NULL DEFAULT NULL COMMENT '置顶截止时间',
  `urgent_until` datetime NULL DEFAULT NULL COMMENT '加急截止时间',
  `boost_until` datetime NULL DEFAULT NULL COMMENT '加速截止时间',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tutor_teacher_resume_user_status` (`user_id`, `status`) USING BTREE,
  KEY `idx_tutor_teacher_resume_audit` (`audit_status`, `create_time`) USING BTREE,
  KEY `idx_tutor_teacher_resume_square` (`city_code`, `status`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '家教教师简历表';
